channels:
  - conda-forge
dependencies:
  - ase
  - coveralls
  - coverage
  - codacy-coverage
  - damask
  - matplotlib
  - fenics
  - mshr
  - numpy
  - pyiron
  - pyiron-data
  - pyvista
  - scipy
  - seaborn
  - scikit-image
  - papermill
  - pip:
    - git+https://github.com/pyiron/pyiron_continuum.git
