channels:
  - conda-forge
dependencies:
  - ase
  - coveralls
  - coverage
  - codacy-coverage
  - damask
  - matplotlib
  - fenics
  - mshr
  - numpy
  - pyiron
  - scipy
  - seaborn
  - scikit-image
  - papermill
